### ISSUE TITLE
easy toggling of icons

### ISSUE THREAD

**Issue by JulienMaille** [mguludag/QEasySettings#1]
That's cool stuff, especially the autoFusion skin.
I was wondering if you have any idea how to handle icon set toggling when switching from dark to light theme?
I've looked at the `QIcon::setThemeName();` but it doesn't seems to work under Windows and icons won't show in designer.

**Comment by mguludag** [comment]
I'm using the signal `notifyPalette(bool isLight);` and change the icons by isLight parameter.

**Comment by JulienMaille** [comment]
thank you, I was hoping you had a standard solution that can update all icons at once
